services:
  cco-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    image: cco-mcp:latest
    container_name: cco-mcp-server
    ports:
      - "8660:8080"
    environment:
      - PORT=8080
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s